---
- name: Apache server installed
  hosts: web

  tasks:
  - name: Gather service facts
    ansible.builtin.service_facts
    
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: false
      state: stopped

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: false
      state: enabled
      immediate: false
    when:
      - ansible_facts['services']['firewalld.service']['status'] == 'running'

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
