---
- name: latest Apache version installed
  yum:
    name: httpd
    state: latest
  notify: apache-restart

- name: latest firewalld version installed
  yum:
    name: firewalld
    state: latest

- name: firewalld enabled and running
  service:
    name: firewalld
    enabled: false
    state: stopped

- name: firewalld permits http service
  firewalld:
    service: http
    permanent: false
    state: enabled
    immediate: false

- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started

- name: Ensure proper Apache configuration
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
  notify: apache-restart

- name: Deploy index.html from template
  template:
    src: "{{ stage }}_index.html.j2"
    dest: /var/www/html/index.html
  notify: apache-restart
